
name: Callable reusable workflow

on:
  workflow_call:
    inputs:

      # Required for 'Workaround 3 Dynamic'
      ref:
        description: 'Git reference - branch, tag, or commit SHA of this file in this repository to use by the caller'
        required: true
        type: string

env:
  # Put the repo owner and name this file is contained in here
  repository: etas-eng/vsps_infra_playground

jobs:
  run_callable_workflow_steps:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Checkout callable repository 'Workaround 3 Dynamic'
        uses: actions/checkout@v6
        with:
          repository: ${{ env.repository }}
          ref: ${{ inputs.ref }}
          path: .github/.reuse_gha_assets/${{ env.repository }}/${{ inputs.ref }}

      # Cannot use this code as the "uses" must have a static value
      # - name: Call Reusable Action from this Repo
      #   uses: ./.github/.reuse_gha_assets/${{ env.repository }}/${{ inputs.ref }}/.github/actions/callable
      - name: Call Reusable Action from this Repo 'Workaround 4'
        uses: jenseng/dynamic-uses@v1.1.1
        with:
          uses: etas-eng/vsps_infra_playground/.github/actions/callable@${{ inputs.ref }}
          with: |
            ref: ${{ inputs.ref }}

      - name: Call script from the repository
        shell: bash
        run: |
          echo "::group::  Call script from the repository"

          # Call the script using relative path
          chmod +x ./.github/.reuse_gha_assets/${{ env.repository }}/${{ inputs.ref }}/.github/scripts/script.sh
          ./.github/.reuse_gha_assets/${{ env.repository }}/${{ inputs.ref }}/.github/scripts/script.sh

          echo "::endgroup::"

      - name: Checkout callable repository 'Workaround 3 Static'
        uses: actions/checkout@v6
        with:
          repository: ${{ env.repository }}
          ref: ${{ inputs.ref }}
          path: .github/.reuse_gha_assets/${{ env.repository }}

      - name: Call Reusable Action from this Repo 'Workaround 3 Static'
        uses: ./.github/.reuse_gha_assets/etas-eng/vsps_infra_playground/.github/actions/callable_wa3static

  run_nested_callable_workflow:
    uses: ./.github/workflows/callable_nested.yml
    with:
      ref: ${{ inputs.ref }}
