name: Test Caller uses local actions and workflows

on:
  push:
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  call-local-action:
    runs-on: ${{ vars.runner_labels_ghub_standard_x64 && fromJSON(vars.runner_labels_ghub_standard_x64) || 'ubuntu-latest' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Call local action
        uses: ./.github/actions/callable
        with:
          ref: ${{ github.workflow_sha }}

  call-local-script:
    runs-on: ${{ vars.runner_labels_ghub_standard_x64 && fromJSON(vars.runner_labels_ghub_standard_x64) || 'ubuntu-latest' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Call local script
        shell: bash
        run: |
          echo "::group::  Call local script"

          chmod +x ./.github/scripts/script.sh
          ./.github/scripts/script.sh

          echo "::endgroup::"

  call-local-workflow:
    uses: ./.github/workflows/callable.yml
    with:
      ref: ${{ github.workflow_sha }}
