name: Test Caller uses remote actions and workflows

on:
  push:
  workflow_dispatch:
    inputs:
      central_gha_assets_repo:
        description: 'Repository owner/name for same org (e.g., etas-eng/vsps_infra_playground)'
        required: true
        default: 'etas-eng/vsps_infra_playground'
        type: string
      central_gha_assets_repo_ref:
        description: 'Git reference for same org (branch, tag, or commit)'
        required: true
        default: 'tml2si'
        type: string
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CENTRAL_GHA_ASSETS_REPO: ${{ inputs.central_gha_assets_repo || 'etas-eng/vsps_infra_playground' }}
  CENTRAL_GHA_ASSETS_REPO_REF: ${{ inputs.central_gha_assets_repo_ref || 'tml2si' }}

jobs:

  call-remote-action-same-org:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v6

      - name: Check if repository already checked out 'Workaround 3 Dynamic'
        id: repo-check
        shell: bash
        run: |
          echo "::group::  Check if repository already checked out 'Workaround 3 Dynamic'"

          repo_path=".github/.reuse/${{ env.CENTRAL_GHA_ASSETS_REPO }}/${{ env.CENTRAL_GHA_ASSETS_REPO_REF }}"
          if [ -d "$repo_path" ]; then
            echo "exists=true" >> "$GITHUB_OUTPUT"
          else
            echo "exists=false" >> "$GITHUB_OUTPUT"
          fi

          echo "::endgroup::"

      - name: Checkout callable repository 'Workaround 3 Dynamic'
        if: steps.repo-check.outputs.exists == 'false'
        uses: actions/checkout@v6
        with:
          repository: ${{ env.CENTRAL_GHA_ASSETS_REPO }}
          ref: ${{ env.CENTRAL_GHA_ASSETS_REPO_REF }}
          path: .github/.reuse/${{ env.CENTRAL_GHA_ASSETS_REPO }}/${{ env.CENTRAL_GHA_ASSETS_REPO_REF }}

      # Next call does not work since the "uses" must be a static string
      # - name: Call remote action using relative path
      #   uses: ./.github/.reuse/${{ inputs.central_gha_assets_repo }}/${{ inputs.central_gha_assets_repo_ref }}/.github/actions/callable

      # This also does not work since the dynamic-uses action does not support local/relative paths of the action to call
      # - name: Call remote action using dynamic path 'Workaround 4'
      #   uses: jenseng/dynamic-uses@v1.1.1
      #   with:
      #     uses: ./.github/.reuse/${{ env.CENTRAL_GHA_ASSETS_REPO }}/${{ env.CENTRAL_GHA_ASSETS_REPO_REF }}/.github/actions/callable
      #     with: |
      #       ref: ${{ inputs.ref }}

      - name: Call script
        shell: bash
        run: |
          echo "::group::  Call script"

          chmod +x ./.github/.reuse/${{ env.CENTRAL_GHA_ASSETS_REPO }}/${{ env.CENTRAL_GHA_ASSETS_REPO_REF }}/.github/scripts/script.sh
          ./.github/.reuse/${{ env.CENTRAL_GHA_ASSETS_REPO }}/${{ env.CENTRAL_GHA_ASSETS_REPO_REF }}/.github/scripts/script.sh

          echo "::endgroup::"

      - name: Call remote action 'Workaround 4'
        uses: jenseng/dynamic-uses@v1.1.1
        with:
          uses: ${{ env.CENTRAL_GHA_ASSETS_REPO }}/.github/actions/callable@${{ env.CENTRAL_GHA_ASSETS_REPO_REF }}
          with: |
            ref: ${{ env.CENTRAL_GHA_ASSETS_REPO_REF }}

  call-remote-workflow-same-org:
    uses: etas-eng/vsps_infra_playground/.github/workflows/callable.yml@tml2si
    with:
      # Must use same ref like in the above uses call
      ref: "tml2si"

